begin;
create extension if not exists pgtap with schema extensions;
set local search_path = extensions, public, pg_catalog;
select plan(16);
select ok(to_regclass('public.chat_rooms') is not null, 'chat_rooms exists');
select ok(to_regclass('public.chat_room_penalties') is not null, 'chat_room_penalties exists');
select ok(to_regclass('public.chat_room_members') is not null, 'chat_room_members exists');
select ok(to_regclass('public.chat_messages') is not null, 'chat_messages exists');
select ok(to_regclass('public.chat_threads') is not null, 'chat_threads exists');
select has_column('public','chat_rooms','id','chat_rooms.id exists');
select has_column('public','chat_rooms','is_active','chat_rooms.is_active exists');
select has_column('public','chat_rooms','is_public','chat_rooms.is_public exists');
select has_column('public','chat_room_penalties','room_id','chat_room_penalties.room_id exists');
select has_column('public','chat_room_penalties','user_id','chat_room_penalties.user_id exists');
select has_column('public','chat_room_penalties','is_active','chat_room_penalties.is_active exists');
select has_column('public','chat_room_penalties','expires_at','chat_room_penalties.expires_at exists');
select has_column('public','chat_messages','thread_id','chat_messages.thread_id exists');
select has_column('public','chat_messages','sender_uid','chat_messages.sender_uid exists');
select has_column('public','chat_messages','media_url','chat_messages.media_url exists');
select ok(exists (select 1 from pg_class where oid='public.chat_rooms'::regclass and relrowsecurity), 'chat_rooms has RLS enabled');
select * from finish();
rollback;
