begin;
select plan(15);
select ok(to_regprocedure('public.send_chat_message(uuid,text,text,text,text,integer,uuid,text,uuid,jsonb)') is not null, 'public.send_chat_message signature exists');
select ok(to_regprocedure('public.send_public_chat_message_v2(uuid,text,text,text,uuid,uuid,text,jsonb,uuid)') is not null, 'public.send_public_chat_message_v2 signature exists');
select ok(to_regprocedure('public.send_room_gift_atomic(uuid,uuid,text,uuid)') is not null, 'public.send_room_gift_atomic signature exists');
select ok(to_regprocedure('public.mark_chat_delivered(text,uuid[])') is not null, 'public.mark_chat_delivered signature exists');
select ok(to_regprocedure('public.mark_chat_thread_read(text)') is not null, 'public.mark_chat_thread_read signature exists');
select ok(to_regprocedure('public.get_room_member_penalties(uuid,uuid)') is not null, 'public.get_room_member_penalties signature exists');
select ok(to_regprocedure('public.sync_chat_member_ban_state(uuid,uuid)') is not null, 'public.sync_chat_member_ban_state signature exists');
select ok(to_regprocedure('public.has_room_permission(uuid,uuid,text)') is not null, 'public.has_room_permission signature exists');
select ok(to_regprocedure('public.get_my_room_controls(uuid)') is not null, 'public.get_my_room_controls signature exists');
select ok(to_regprocedure('public.allow_chat_message(uuid)') is not null, 'public.allow_chat_message signature exists');
select ok(exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='send_chat_message' and not has_function_privilege('anon', p.oid, 'EXECUTE')), 'anon cannot execute send_chat_message');
select ok(exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='send_public_chat_message_v2' and not has_function_privilege('anon', p.oid, 'EXECUTE')), 'anon cannot execute send_public_chat_message_v2');
select ok(exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='send_room_gift_atomic' and not has_function_privilege('anon', p.oid, 'EXECUTE')), 'anon cannot execute send_room_gift_atomic');
select ok(exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='send_chat_message' and has_function_privilege('authenticated', p.oid, 'EXECUTE')), 'authenticated can execute send_chat_message');
select ok(exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='send_public_chat_message_v2' and has_function_privilege('authenticated', p.oid, 'EXECUTE')), 'authenticated can execute send_public_chat_message_v2');
select * from finish();
rollback;
