begin;
create extension if not exists pgtap with schema extensions;
set local search_path = extensions, public, pg_catalog;
select plan(42);
select ok(exists (select 1 from storage.buckets where id = 'avatars'), 'avatars bucket exists');
select ok(exists (select 1 from storage.buckets where id = 'avatars' and coalesce(file_size_limit,0) > 0), 'avatars has a positive size limit');
select ok(exists (select 1 from storage.buckets where id = 'avatars' and coalesce(array_length(allowed_mime_types,1),0) > 0), 'avatars has MIME allow-list');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='INSERT' and coalesce(with_check,'') like '%bucket_id = ''avatars''%'), 'avatars has INSERT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='SELECT' and coalesce(qual,'') like '%bucket_id = ''avatars''%'), 'avatars has SELECT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='UPDATE' and coalesce(qual,'') like '%bucket_id = ''avatars''%'), 'avatars has UPDATE policy for upsert');
select ok(exists (select 1 from storage.buckets where id = 'profile-avatars'), 'profile-avatars bucket exists');
select ok(exists (select 1 from storage.buckets where id = 'profile-avatars' and coalesce(file_size_limit,0) > 0), 'profile-avatars has a positive size limit');
select ok(exists (select 1 from storage.buckets where id = 'profile-avatars' and coalesce(array_length(allowed_mime_types,1),0) > 0), 'profile-avatars has MIME allow-list');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='INSERT' and coalesce(with_check,'') like '%bucket_id = ''profile-avatars''%'), 'profile-avatars has INSERT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='SELECT' and coalesce(qual,'') like '%bucket_id = ''profile-avatars''%'), 'profile-avatars has SELECT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='UPDATE' and coalesce(qual,'') like '%bucket_id = ''profile-avatars''%'), 'profile-avatars has UPDATE policy for upsert');
select ok(exists (select 1 from storage.buckets where id = 'chat-media-plus'), 'chat-media-plus bucket exists');
select ok(exists (select 1 from storage.buckets where id = 'chat-media-plus' and coalesce(file_size_limit,0) > 0), 'chat-media-plus has a positive size limit');
select ok(exists (select 1 from storage.buckets where id = 'chat-media-plus' and coalesce(array_length(allowed_mime_types,1),0) > 0), 'chat-media-plus has MIME allow-list');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='INSERT' and coalesce(with_check,'') like '%bucket_id = ''chat-media-plus''%'), 'chat-media-plus has INSERT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='SELECT' and coalesce(qual,'') like '%bucket_id = ''chat-media-plus''%'), 'chat-media-plus has SELECT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='UPDATE' and coalesce(qual,'') like '%bucket_id = ''chat-media-plus''%'), 'chat-media-plus has UPDATE policy for upsert');
select ok(exists (select 1 from storage.buckets where id = 'store-media'), 'store-media bucket exists');
select ok(exists (select 1 from storage.buckets where id = 'store-media' and coalesce(file_size_limit,0) > 0), 'store-media has a positive size limit');
select ok(exists (select 1 from storage.buckets where id = 'store-media' and coalesce(array_length(allowed_mime_types,1),0) > 0), 'store-media has MIME allow-list');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='INSERT' and coalesce(with_check,'') like '%bucket_id = ''store-media''%'), 'store-media has INSERT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='SELECT' and coalesce(qual,'') like '%bucket_id = ''store-media''%'), 'store-media has SELECT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='UPDATE' and coalesce(qual,'') like '%bucket_id = ''store-media''%'), 'store-media has UPDATE policy for upsert');
select ok(exists (select 1 from storage.buckets where id = 'chat-wallpapers'), 'chat-wallpapers bucket exists');
select ok(exists (select 1 from storage.buckets where id = 'chat-wallpapers' and coalesce(file_size_limit,0) > 0), 'chat-wallpapers has a positive size limit');
select ok(exists (select 1 from storage.buckets where id = 'chat-wallpapers' and coalesce(array_length(allowed_mime_types,1),0) > 0), 'chat-wallpapers has MIME allow-list');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='INSERT' and coalesce(with_check,'') like '%bucket_id = ''chat-wallpapers''%'), 'chat-wallpapers has INSERT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='SELECT' and coalesce(qual,'') like '%bucket_id = ''chat-wallpapers''%'), 'chat-wallpapers has SELECT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='UPDATE' and coalesce(qual,'') like '%bucket_id = ''chat-wallpapers''%'), 'chat-wallpapers has UPDATE policy for upsert');
select ok(exists (select 1 from storage.buckets where id = 'profile-music'), 'profile-music bucket exists');
select ok(exists (select 1 from storage.buckets where id = 'profile-music' and coalesce(file_size_limit,0) > 0), 'profile-music has a positive size limit');
select ok(exists (select 1 from storage.buckets where id = 'profile-music' and coalesce(array_length(allowed_mime_types,1),0) > 0), 'profile-music has MIME allow-list');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='INSERT' and coalesce(with_check,'') like '%bucket_id = ''profile-music''%'), 'profile-music has INSERT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='SELECT' and coalesce(qual,'') like '%bucket_id = ''profile-music''%'), 'profile-music has SELECT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='UPDATE' and coalesce(qual,'') like '%bucket_id = ''profile-music''%'), 'profile-music has UPDATE policy for upsert');
select ok(exists (select 1 from storage.buckets where id = 'garment-service-media'), 'garment-service-media bucket exists');
select ok(exists (select 1 from storage.buckets where id = 'garment-service-media' and coalesce(file_size_limit,0) > 0), 'garment-service-media has a positive size limit');
select ok(exists (select 1 from storage.buckets where id = 'garment-service-media' and coalesce(array_length(allowed_mime_types,1),0) > 0), 'garment-service-media has MIME allow-list');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='INSERT' and coalesce(with_check,'') like '%bucket_id = ''garment-service-media''%'), 'garment-service-media has INSERT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='SELECT' and coalesce(qual,'') like '%bucket_id = ''garment-service-media''%'), 'garment-service-media has SELECT policy');
select ok(exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and cmd='UPDATE' and coalesce(qual,'') like '%bucket_id = ''garment-service-media''%'), 'garment-service-media has UPDATE policy for upsert');
select * from finish();
rollback;
